### ISSUE TITLE
Add lazy evaluation for default values

### ISSUE THREAD

**Issue by nekdenis** [yandextaxitech/binaryprefs#36]
In most cases we do not need to have instance of default value because value already stored for the key. 

For optimisation purposes will be great to extend interface by adding lazy evaluation of default value. And evaluate it only in case if key is not presented in storage.

**Comment by iamironz** [comment]
Please explain what kind of lazy evaluation api do you mean?

**Comment by nekdenis** [comment]
Now app requires providing an instance of defValue even if the actual value is presented in storage. 

```
getPersistable(String key, T defValue)
getString(String key, String defValue)
```
My proposal is to have something like that

```
getString(String key, Provider<String> defValueProvider)
```
where Provider is just a lazy creator of defValue

**Comment by iamironz** [comment]
So... what point of this use case? I cannot understand for what you need to create lazy instance? Here I meant that `defValue` is just a dummy value for evaluating non-existence of persisted data and nothing else. You should never create variable default objects with different data by specific use case because this worst for application logic understanding.

**Comment by iamironz** [comment]
Closed because useless right now.
