### ISSUE TITLE
Preferences should be instantiated in the main thread.

### ISSUE THREAD

**Issue by IamEgor** [yandextaxitech/binaryprefs#44]
Could you please explain the purpose of this check?
https://github.com/yandextaxitech/binaryprefs/blob/173b268d5c2565795ecfca69cb863263895b0f04/library/src/main/java/com/ironz/binaryprefs/BinaryPreferencesBuilder.java#L256-L258

**Comment by iamironz** [comment]
Hi ! 

First: 
You should guarantee that migration performs not in the parallel. Otherwise it may cause inconsistency after storing migrated values because you can't determinate ordering of operations from multiple threads while instantiates multiple instances of preferences.

Second:
Generally you should persist and fetch all values from preferences on main thread, it does not affect any performance because all data stores in-memory and disk IO performs in separated background thread queue.

Thanks for question.

**Comment by IamEgor** [comment]
Thanks for the reply!

**Comment by iismagilov** [comment]
Hi @iamironz! 
I'm migrating project to binaryprefs but faced with main thread restriction. And that is only one thing that prevents me from using this cool lib :) Basically on my project it's guaranteed that migration will be performed correctly. Also prefs in my project are part of data layer which is completely async. Would be better to make option to  build Preferences without main thread checking. What do you think if I create PR to fix that?

**Comment by nekdenis** [comment]
This check requires to use Looper from android SDK so now it is impossible to use that library in JVM tests

**Comment by iamironz** [comment]
Please, don't test my code inside yours unit tests, use repo interfaces

**Comment by iamironz** [comment]
@iismagilov hey, PR is already approved and will be merged in the next release

**Comment by iismagilov** [comment]
@iamironz Cool! I've just updated PR with addition description for new `allowBuildOnBackgroundThread()` builder method.

**Comment by iamironz** [comment]
Merged! https://github.com/yandextaxitech/binaryprefs/pull/46
